language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libboost-all-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

install:
  - git clone https://github.com/physycom/sysconfig.git
  - export WORKSPACE=$(pwd)
  - mkdir build && cd build

script:
  - cmake ..
  - cmake --build .
