language: cpp

os:
  - linux
  - osx

compiler: 
    - gcc
    - clang

addons:
  apt:
    packages:
    - libboost-all-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:

install:

script:
  - mkdir build && cd build && cmake .. && cmake --build . --target install && cd ..

