language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libboost-all-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:

install:
  - git clone https://github.com/physycom/sysconfig.git
  - export SYSCONFIG_PATH=$(pwd)/sysconfig
  - mkdir build && cd build

script:
  - cmake .. "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${SYSCONFIG_PATH}/cmake/physycom_toolchain.cmake" && cmake --build .
